apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalrappdeploy
  labels:
    app: signalr
spec:
  replicas: 1
  selector:
    matchLabels:
      service: signalrappdeploy
  template:
    metadata:
      labels:
        app: signalr
        service: signalrappdeploy
    spec:
      containers: 
        - name: signalrappdeploy
          image: plcontainerregistry.azurecr.io/petolucsignalr:latest       
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80   
            - name: WebApiBaseAddress
              value: http://signalr
---
apiVersion: v1
kind: Service
metadata:
  name: signalrappdeploy
  labels:
    app: signalr
    service: signalrappdeploy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: signalrappdeploy